# Generated by Django 5.1.4 on 2026-08-19 19:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canal', models.CharField(choices=[('web', 'Web'), ('telegram', 'Telegram'), ('correo', 'Correo')], default='web', max_length=16)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pendiente', 'Pendiente'), ('cerrada', 'Cerrada')], default='activa', max_length=16)),
                ('intencion', models.CharField(blank=True, max_length=100)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('usuario', 'Usuario'), ('alma', 'Alma'), ('agente_humano', 'Agente humano')], max_length=16)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
