# Generated by Django 5.1.4 on 2026-08-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_mensaje_respondido'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='imagen_base64',
            field=models.TextField(blank=True, default=''),
        ),
    ]
