# Generated by Django 5.1.4 on 2026-08-19 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('justificacion', models.TextField(blank=True)),
                ('puntaje', models.DecimalField(decimal_places=3, max_digits=4)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='catalog.producto')),
                ('recuerdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='memories.recuerdo')),
            ],
            options={
                'ordering': ['-puntaje'],
            },
        ),
    ]
