# Generated by Django 5.1.4 on 2026-08-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='advertencias',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='requiere_revision_humana',
            field=models.BooleanField(default=False),
        ),
    ]
