# Generated by Django 5.2.17 on 2026-08-24 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_alter_ejecucionagente_conversacion'),
        ('evaluations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuenteConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(blank=True, default='', max_length=100)),
                ('version', models.CharField(default='v1', max_length=30)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('desactualizada', 'Desactualizada'), ('archivada', 'Archivada')], default='activa', max_length=20)),
                ('url_o_referencia', models.CharField(blank=True, default='', max_length=500)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CasoPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente', models.CharField(choices=[('orquestador', 'Orquestador'), ('acompanamiento', 'Acompañamiento'), ('extraccion', 'Extracción'), ('creativo', 'Creativo'), ('viabilidad', 'Viabilidad'), ('recomendacion', 'Recomendación'), ('proveedores', 'Proveedores'), ('cotizacion', 'Cotización'), ('pedidos', 'Pedidos'), ('memorial', 'Memorial'), ('seguridad', 'Seguridad'), ('evaluador', 'Evaluador')], max_length=32)),
                ('nombre', models.CharField(max_length=200)),
                ('entrada', models.TextField(help_text='Mensaje/escenario de entrada a probar.')),
                ('resultado_esperado', models.TextField(blank=True, default='')),
                ('resultado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('requiere_revision', 'Requiere revisión')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_prueba_revisados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CorreccionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_error', models.CharField(choices=[('informacion_incorrecta', 'Información incorrecta'), ('tono_inadecuado', 'Tono inadecuado'), ('regla_de_negocio', 'Violación de regla de negocio'), ('fuera_de_alcance', 'Fuera de alcance'), ('otro', 'Otro')], max_length=30)),
                ('respuesta_esperada', models.TextField()),
                ('comentario', models.TextField(blank=True, default='')),
                ('decision', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobar_para_dataset', 'Aprobar para dataset'), ('descartar', 'Descartar')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correcciones', to='agents.ejecucionagente')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcciones_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
