# Generated by Django 5.1.4 on 2026-08-19 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorialDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('visibilidad', models.CharField(choices=[('privado', 'Privado'), ('con_enlace', 'Con enlace'), ('publico', 'Público')], default='privado', max_length=16)),
                ('qr_url', models.URLField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('recuerdo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memorial', to='memories.recuerdo')),
            ],
        ),
    ]
