# Generated by Django 5.1.4 on 2026-08-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorialdigital',
            name='biografia',
            field=models.TextField(blank=True),
        ),
    ]
