# Generated by Django 5.1.4 on 2026-08-19 15:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('documento', 'Documento'), ('audio', 'Audio'), ('video', 'Video')], max_length=16)),
                ('url', models.URLField()),
                ('checksum', models.CharField(max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recuerdo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('persona_recordada', models.CharField(blank=True, max_length=150)),
                ('historia', models.TextField(blank=True)),
                ('privacidad', models.CharField(choices=[('privado', 'Privado'), ('compartido', 'Compartido'), ('publico', 'Público')], default='privado', max_length=16)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuerdos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ObjetoMemoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=100)),
                ('nivel_transformacion', models.CharField(blank=True, max_length=100)),
                ('archivos', models.ManyToManyField(blank=True, related_name='objetos_memoria', to='memories.archivo')),
                ('recuerdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos', to='memories.recuerdo')),
            ],
        ),
    ]
