# Generated by Django 5.1.4 on 2026-08-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetomemoria',
            name='anio_aproximado',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='objetomemoria',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='objetomemoria',
            name='estado',
            field=models.TextField(blank=True),
        ),
    ]
