# Generated by Django 5.1.4 on 2026-08-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_objetomemoria_anio_aproximado_objetomemoria_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetomemoria',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='objetomemoria',
            name='fotos_base64',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
