# Generated by Django 5.2.17 on 2026-08-24 16:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_eventopedido_evidencias_base64_mensajepedido_resena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comision_pct', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('monto_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=16)),
                ('fecha_estimada', models.DateField(blank=True, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='orders.pedido')),
            ],
        ),
    ]
