# Generated by Django 5.1.4 on 2026-08-19 19:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionAgente',
            fields=[
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agente', models.CharField(choices=[('orquestador', 'Orquestador'), ('acompanamiento', 'Acompañamiento'), ('extraccion', 'Extracción'), ('creativo', 'Creativo'), ('viabilidad', 'Viabilidad'), ('recomendacion', 'Recomendación'), ('proveedores', 'Proveedores'), ('cotizacion', 'Cotización'), ('pedidos', 'Pedidos'), ('memorial', 'Memorial'), ('seguridad', 'Seguridad'), ('evaluador', 'Evaluador')], max_length=32)),
                ('agent_version', models.CharField(default='v1', max_length=32)),
                ('estado', models.CharField(choices=[('en_progreso', 'En progreso'), ('completado', 'Completado'), ('fallido', 'Fallido')], default='en_progreso', max_length=16)),
                ('reply', models.TextField(blank=True)),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('tools_used', models.JSONField(blank=True, default=list)),
                ('latencia_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('evaluation_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('evaluation_flags', models.JSONField(blank=True, default=list)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
