# Generated by Django 5.1.4 on 2026-08-21 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
        ('conversations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejecucionagente',
            name='conversacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones_agente', to='conversations.conversacion'),
        ),
    ]
