# Generated by Django 5.1.4 on 2026-08-19 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_taller', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado_validacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado'), ('suspendido', 'Suspendido')], default='pendiente', max_length=16)),
                ('calificacion', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proveedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CapacidadProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('tiempo_estimado_dias', models.PositiveIntegerField(default=7)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacidades', to='catalog.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacidades', to='providers.proveedor')),
            ],
            options={
                'unique_together': {('proveedor', 'producto', 'material')},
            },
        ),
    ]
