# Generated by Django 5.2.17 on 2026-08-24 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='capacidad_maxima',
            field=models.PositiveIntegerField(default=5, help_text='Pedidos simultáneos que el taller puede atender.'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='DiaBloqueadoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_bloqueados', to='providers.proveedor')),
            ],
            options={
                'ordering': ['fecha'],
                'unique_together': {('proveedor', 'fecha')},
            },
        ),
    ]
