# Generated by Django 5.2.17 on 2026-08-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_proveedor_capacidad_maxima_proveedor_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='anios_experiencia',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='horario_atencion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
