# Generated by Django 5.2.17 on 2026-08-24 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_proveedor_anios_experiencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('portafolio', 'Portafolio'), ('documento_legal', 'Documento legal')], max_length=20)),
                ('nombre_archivo', models.CharField(blank=True, default='', max_length=255)),
                ('archivo_base64', models.TextField()),
                ('estado_revision', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=16)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='providers.proveedor')),
            ],
        ),
    ]
