# Generated by Django 5.1.4 on 2026-08-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
