# Generated by Django 5.1.4 on 2026-08-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_perfil_telegram_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCanalTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_update_id', models.BigIntegerField(default=0)),
                ('bloqueado_desde', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
