# Generated by Django 5.1.4 on 2026-08-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_estadocanaltelegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
