# Generated by Django 5.2.17 on 2026-08-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_perfil_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='Reviive SAS', max_length=150)),
                ('correo_contacto', models.EmailField(default='contacto@reviive.com', max_length=254)),
                ('telefono_contacto', models.CharField(blank=True, default='', max_length=30)),
                ('zona_horaria', models.CharField(default='America/Bogota', max_length=50)),
                ('moneda', models.CharField(default='COP', max_length=10)),
                ('idioma', models.CharField(default='es', max_length=10)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
