# Generated by Django 5.2.17 on 2026-08-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_codigovinculaciontelegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('canal', models.CharField(choices=[('correo', 'Correo'), ('telegram', 'Telegram')], default='correo', max_length=16)),
                ('asunto', models.CharField(blank=True, default='', max_length=200)),
                ('cuerpo', models.TextField(blank=True, default='')),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
