# Generated by Django 5.1.4 on 2026-08-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('motivo', models.CharField(blank=True, choices=[('restauracion', 'Restauración'), ('preservacion', 'Preservación'), ('transformacion', 'Transformación'), ('otra', 'Otra consulta')], default='', max_length=20)),
                ('mensaje', models.TextField()),
                ('foto_base64', models.TextField(blank=True, default='')),
                ('atendido', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
