# Generated by Django 5.1.4 on 2026-08-19 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memories', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vigencia', models.DateField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('vencida', 'Vencida'), ('rechazada', 'Rechazada')], default='borrador', max_length=16)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='providers.proveedor')),
                ('recuerdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='memories.recuerdo')),
            ],
        ),
    ]
